version: "3.4"

services:
    client:
        build:
          context: ./src/client
          dockerfile: Dockerfile
        image: jjs98/articlestore-client
        ports:
          - "5000:80"

    api:
        build:
          context: ./src/server/ArticleStore
          dockerfile: Dockerfile
        image: jjs98/articlestore-api
        environment:
          ConnectionStrings__Default: Server=db;Port=5432;Database=ArticleStore;User Id=postgres;Password=S3cur3P@ssW0rd!;
        ports:
          - "8081:80"
        depends_on:
          - db

    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: S3cur3P@ssW0rd!
        ports:
          - '5432:5432'

    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080