version: "3.4"

services:
    client:
        build:
          context: ./src/client
          dockerfile: Dockerfile
        ports:
          - "5000:80"

    api:
        build:
          context: ./src/server/ArticleStore
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"